@domain_dev = square.ukp-lab.localhost
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMT0NBTF9TUVVBUkVfVVNFUiIsImlzcyI6Ii9MT0NBTF9TUVVBUkVfUkVBTE0iLCJleHAiOjk5OTk5OTk5OTl9.DJZonR1DWkX4do5rR4rx_N63wp-P-zWlQxNPo2c3xJy2dZ7gWS0c9nR16A9O7rAYX7M9D_4g2qcHzhhuyCpBkKWzpVRn2w6N5PaU1URu0NgoIfXA20O0KRtRLsX7ubWBya-HA5Zp_6Rc2qbxVv1OsbTOzAEuDsb5NMC4r5mZfCpQSQheR9BCk3ZF0d9REvziReJiO5nwV2wsdILTWiQoQYm1HukOQQVB0lZfGeiERzz14ztmSivzRSxnCy_NWrK6b8oK5uOPSWEtzwqkGWeAkO97obPiK5ukQuB1eMPE0vktENlRlYs7mF6SIayYj2DZ13YYbBd67qQfOGChvlp0zghBvZCtovuEQDe9tquoHE3IGLItbeF7IOEd7hz5g6HExIKZEB4AiNuqJ0LKzDW_19-Houjy09Al1gUbpL5xNfncXYxS_dbniMnRddJKDyAvNW907aBs7GHZGUctrmIXtVtiyGLsKlb9jrdCUDJWly0evmCyF_DuFUt2WRV-g1k0lI9GG4Mgs5WXxFcCxpIK8G4Q4B9Ww4jN9b6jp9pGNH-FaV2ttmhHLb4PB9X6W__vs7FsA4a8Dj-xdC7hvRQfakkNCXrnj6ADYYNjpeaBBYv2PCxxoqHZHbwLbxC07BGBXGAHREJt8uZbIXf5N5Mf31TULOuDWmDIjGIl7OfDM8U

### Check heartbeat
## @name health
GET {{domain_dev}}/api/main/health/heartbeat
Authorization: Bearer {{token}}

###
# @name sentence-transformer
POST {{domain_dev}}/api/main/msmarco-distilbert-base-tas-b/embedding
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "input": [
    "Do aliens exist?"
  ],
  "is_preprocessed": false,
  "preprocessing_kwargs": {},
  "model_kwargs": {},
  "task_kwargs": {},
  "adapter_name": ""
}

###
# @name squad_bert_onnx
POST {{domain_dev}}/api/main/bert-base-uncased-pf-squad-onnx/question-answering
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "input": [
 ["Who stars in The Matrix?",
    "The Matrix is a 1999 science fiction action's film written 'and' directed by The 'Wachowskis', starring Keanu Reeves, Laurence."]
 ],
 "is_preprocessed": false,
 "preprocessing_kwargs": {},
 "model_kwargs": {},
 "task_kwargs": {},
 "adapter_name": ""
}

###
# @name squad_roberta_onnx
POST {{domain_dev}}/api/main/roberta-base-uncased-pf-squad-onnx/question-answering
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "input": [
 [
  "Who stars in The Matrix?",
    "The Matrix is a 1999 science fiction action's film written 'and' directed by The 'Wachowskis', starring Keanu Reeves, Laurence."]
 ],
 "is_preprocessed": false,
 "preprocessing_kwargs": {},
 "model_kwargs": {},
 "task_kwargs": {},
 "adapter_name": ""
}



####
# @name get_results
GET {{domain_dev}}/api/main/task_result/9688f0fc-766e-43f2-aa3f-5f98475972f2
Authorization: Bearer {{token}}
Content-Type: application/json