@domain_dev = square.ukp-lab.localhost
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJMT0NBTF9TUVVBUkVfVVNFUiIsImlzcyI6Ii9MT0NBTF9TUVVBUkVfUkVBTE0iLCJleHAiOjk5OTk5OTk5OTl9.LikKZZoeyBeUC8fKG0HaIxinIu-Aq1WhABlkRiDPvE-jS8v06NVqztLXGgXp2DIigdzZ360pRK2_B7HI3PANto11KO-uHVOthC8_FGmKhAk5ZbfDaLTC1VX1YqZyUrJEulfvbZsjCT6ba-hcfYpFPGX2wzjHnPoHrHm6wr3bh39x6cE6iMmhe-svp3E-g6VAgAdMB_HhLoTQYtPpg3XK2Ozfm64Ejdsnzrh3Dwgf0a1BNTp_GtWw2cE4HR1Tvna0pRcUgBbQF4HfzOfaXZ6_bf141d3FXBhXNq9KlRBnZCHBpmuBpWAO_PyVe30FltUQ-a0n-5bXn6i2ZdF5E4A298MwnJSua9KIAgN3e6qPIMLexXtodYlqItdcmnLC0T5Pli7WnURRW4W3uXP2flRu68fyupzQ8RCIDYlrGk-lATUF6ffs-PsB8nRAouUvhoiQREiFquMHTEHW0FdUumusjDWIjffFFHCnjPtoCjDXwCbf8C4AiHnPeN4QG69Fynnvs8l83RYp8jbTCpe0t3ox4yu1ruDHhcAQ_QFM3IUB8n9lukpWnyijB5eFESV3bd2Y3ABMp_jaGi7JKWbYr6zoVSYp_hQnYqsR05EXrG30mYDDuPO_dDZ1jHz70-HOd6Xbq_xlj_Wob1B5CTqtqOaa1T9XaVJ0GaLFyL3KUQEA8zo

### Check heartbeat
## @name health
GET {{domain_dev}}/api/main/health/heartbeat
Authorization: Bearer {{token}}

###
# @name sentence-transformer
POST {{domain_dev}}/api/main/msmarco-distilbert-base-tas-b/embedding
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "input": [
    "Do aliens exist?"
  ],
  "is_preprocessed": false,
  "preprocessing_kwargs": {},
  "model_kwargs": {},
  "task_kwargs": {},
  "adapter_name": ""
}

###
# @name squad_bert_onnx
POST {{domain_dev}}/api/main/bert-base-uncased-pf-squad-onnx/question-answering
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "input": [
 ["Who stars in The Matrix?",
    "The Matrix is a 1999 science fiction action's film written 'and' directed by The 'Wachowskis', starring Keanu Reeves, Laurence."]
 ],
 "is_preprocessed": false,
 "preprocessing_kwargs": {},
 "model_kwargs": {},
 "task_kwargs": {},
 "adapter_name": ""
}

###
# @name squad_roberta_onnx
POST {{domain_dev}}/api/main/roberta-base-pf-squad-onnx/question-answering
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "input": [
 [
  "Who stars in The Matrix?",
    "The Matrix is a 1999 science fiction action's film written 'and' directed by The 'Wachowskis', starring Keanu Reeves, Laurence."]
 ],
 "is_preprocessed": false,
 "preprocessing_kwargs": {},
 "model_kwargs": {},
 "task_kwargs": {},
 "adapter_name": ""
}

###
# @name boolq_roberta_onnx
POST {{domain_dev}}/api/main/roberta-base-pf-boolq-onnx/sequence-classification
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "input": [
 [
  "is a wolverine the same as a badger",
  "Badgers are short-legged omnivores in the family Mustelidae, which also includes the otters, polecats, weasels, and wolverines. They belong to the caniform suborder of carnivoran mammals. The 11 species of badgers are grouped in three subfamilies: Melinae (Eurasian badgers), Mellivorinae (the honey badger or ratel), and Taxideinae (the American badger). The Asiatic stink badgers of the genus Mydaus were formerly included within Melinae (and thus Mustelidae), but recent genetic evidence indicates these are actually members of the skunk family, placing them in the taxonomic family Mephitidae."]
 ],
 "is_preprocessed": false,
 "preprocessing_kwargs": {},
 "model_kwargs": {},
 "task_kwargs": {},
 "adapter_name": ""
}

###
# @name quartz_roberta_onnx
POST {{domain_dev}}/api/main/roberta-base-pf-quartz-onnx/sequence-classification
Authorization: Bearer {{token}}
Content-Type: application/json

{
 "input": [
 [
  "What animal has the most hair? Fish",
    "Fish are typically not hairy. Horses have 100g of hair. Cats have 10g of hair. Tigers have 12g of hair."
 ],
 [
  "What animal has the most hair? Cats",
    "Fish are typically not hairy. Horses have 100g of hair. Cats have 10g of hair. Tigers have 12g of hair."
  ],
  [
    "What animal has the most hair? Horses",
    "Fish are typically not hairy. Horses have 100g of hair. Cats have 10g of hair. Tigers have 12g of hair."
  ],
   [
    "What animal has the most hair? Tigers",
  "Fish are typically not hairy. Horses have 100g of hair. Cats have 10g of hair. Tigers have 12g of hair."
  ]
 ],
 "is_preprocessed": false,
 "preprocessing_kwargs": {},
 "model_kwargs": {},
 "task_kwargs": {
  "multiple_choice": true
 },
 "adapter_name": ""
}


####
# @name get_results
GET {{domain_dev}}/api/main/task_result/23c3b743-9e21-4a6a-bf77-593684b9f9bc
Authorization: Bearer {{token}}
Content-Type: application/json